### ISSUE TITLE
How to use with Travis?

### ISSUE THREAD

**Issue by torbjoernk** [octopress/deploy#32]
Is anybody already using this gem for deploying a GitHub project or user/organization page via TravisCI?

I'm trying to set one up ([Parallel-in-Time/parallel-in-time.github.io](https://github.com/Parallel-in-Time/parallel-in-time.github.io)) but failing hard with Travis' default behaviour of running `bundle install --path=${BUNDLE_PATH:-vendor/bundle}`. It somehow assumes one is using `rake` for all the CI tasks and not a binary provided by a gem.

**Comment by plttn** [comment]
@imathis / @torbjoernk considering this is an issue from last year, not really sure if you're still having trouble with it, but i've written a blog post (designed for 2.0, but the general bit that you'll need to work with remains the same.)

blog: https://plttn.me/octopress/2015/01/17/yet-another-octopress-2-dot-0-plus-travis-ci-guide/

Short version: 
Use something like this for your Travis config: https://gist.github.com/plttn/655c1a3bce8ab3275a4b. 
(I deploy in script rather than after success, as a failure in after_success won't flip the build over to failing)

Generate a SSH keypair, and add the public to github's settings, and then edit the private key as follows: replace all newlines with `\n`, and then escape that to `\\n`. In your Travis repo settings, make a new environment variable named `DEPLOY_PRIVATE_KEY`, and paste the private key, which should now be one line, into the variable box. 

I've got a proof of concept on travis-ci.org (at the moment it's suffering from an ssh-agent bug, which I had resolved on my primary site, but i can't seem to access my build history right now to determine what I did to fix it.) at https://travis-ci.org/plttn/octopress3.

**Comment by plttn** [comment]
Realized my bug.

Ensure that ssh-agent is not running before generating the key you intend to deploy with. For some reason, leaving it running and generating a key causes ssh-agent on Travis to ask for a passphrase.

Commit on Github: https://github.com/plttn/octopress3/commit/520ce15af5362e880ef6ca16c37ee8f4133926bc

Build on Travis:
https://travis-ci.org/plttn/octopress3/builds/47474897

**Comment by imathis** [comment]
Thanks so much for sharing this with me. The last time I looked at it, either it wasn't possible (with public projects) or I'd given it up because it didn't seem to work. I'll give it a try and if I'm successful, I'll update the documentation with a guide. Thanks!

**Comment by plttn** [comment]
No problem. I went through around 50 builds on my private repo trying to get this all worked out, so I figured I'd help everyone else out.
