### ISSUE TITLE
Add CloudFront invalidation after upload

### ISSUE THREAD

**Issue by victor** [octopress/deploy#47]
For sites that are served with S3+CloudFront (for example, any which is served via https) there's an extra step needed after upload, which is invalidating the affected resources so that they are purged from CloudFront's cache.

Please add a new step to invalidate the cache when a CloudFront distribution id is included in the deploy configuration.

**Comment by imathis** [comment]
If you can provide a pull-request, or point me to some AWS SDK docs I'll be happy to add this. I don't use CloudFront and I don't know the proper way to accomplish this.

**Comment by magikid** [comment]
Here are the docs I found related to their cache invalidation: http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/CreateInvalidation.html. They also suggest it may be easier to just version assets here: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

**Comment by imathis** [comment]
@magikid Thanks for the research. I must say, I don't really use AWS for hosting sites. To me, it doesn't seem to be what it's intended for. I don't like the idea that all traffic is a direct cost. I prefer GitHub pages or traditional servers with high transfer caps and low monthly fees. I've added this feature because so many people request it, perhaps because somehow it's easier for them to set up than other hosting methods, I don't know. That being said, I'm not that motivated to work on CloudFront, and since I don't use it, it's probably not good for me to. If you're interested in helping improve CloudFront deployment, I'm more than happy to review pull requests.

**Comment by magikid** [comment]
Ok. I'll poke around on it some this week and see if I can get it working.

**Comment by imathis** [comment]
:metal:

**Comment by imathis** [comment]
I've shipped version 1.2.0 with #49 merged in. Thanks everyone!
